# DataFrame Basics

In [2]:
## importing the library 
import pandas as pd

In [3]:
#Loading the data
df = pd.read_csv("Airline Dataset Updated - v2.csv")
df.head() ## prints the 1st five rows

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time

In [4]:
df.tail() # prints the last 5 rows

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
98614,hnGQ62,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12-11-2022,HAA,Pammie Kingscote,Cancelled
98615,2omEzh,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Dorice Lochran,Cancelled
98616,VUPiVG,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,09-10-2022,ABC,Gearalt Main,On Time
98617,E47NtS,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Judon Chasle,Cancelled
98618,8JYEcz,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Auguste Tindley,Delayed

In [5]:
## get the rows and columns of the dataframe
df.shape

(98619, 15)

In [6]:
df[1:3] ## performing slicing operation

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time

In [7]:
df.columns ## printing the column names

Index(['Passenger ID', 'First Name', 'Last Name', 'Gender', 'Age',
       'Nationality', 'Airport Name', 'Airport Country Code', 'Country Name',
       'Airport Continent', 'Continents', 'Departure Date', 'Arrival Airport',
       'Pilot Name', 'Flight Status'],
      dtype='object')

In [8]:
df['Flight Status'] ## gives length of the column and its datatype

0          On Time
1          On Time
2          On Time
3          Delayed
4          On Time
           ...
98614    Cancelled
98615    Cancelled
98616      On Time
98617    Cancelled
98618      Delayed
Name: Flight Status, Length: 98619, dtype: object

In [9]:
## to get only datatype of the column 
type(df['Flight Status'])

pandas.core.series.Series

In [10]:
df[['Flight Status', 'Departure Date','Pilot Name']]

      Flight Status Departure Date           Pilot Name
0           On Time      6/28/2022  Fransisco Hazeldine
1           On Time     12/26/2022      Marla Parsonage
2           On Time      1/18/2022         Rhonda Amber
3           Delayed      9/16/2022       Kacie Commucci
4           On Time      2/25/2022          Ebonee Tree
...             ...            ...                  ...
98614     Cancelled     12-11-2022     Pammie Kingscote
98615     Cancelled     10/30/2022       Dorice Lochran
98616       On Time     09-10-2022         Gearalt Main
98617     Cancelled     10/26/2022         Judon Chasle
98618       Delayed      4/16/2022      Auguste Tindley

[98619 rows x 3 columns]

# operations on the dataframe

In [12]:
df['Age'].max()

90

In [13]:
df[df['Age'] <= 10]

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
25,f27tyG,Joellyn,Stutter,Female,8,Croatia,Timbedra Airport,MR,Mauritania,AF,Africa,2/19/2022,TMD,Janaya Retchford,On Time
28,uoKrdd,Jessamyn,Buddles,Female,6,Peru,Gamboma Airport,CG,Congo,AF,Africa,04-09-2022,GMM,Beau Stevens,Delayed
35,L0fKMv,Gardiner,Ferbrache,Male,9,Sweden,Gora Airstrip,PG,Papua New Guinea,OC,Oceania,6/25/2022,GOC,Pamela Franiak,On Time
71,udSiKS,Fidelio,Guerry,Male,3,China,Yuruf Airport,ID,Indonesia,AS,Asia,05-02-2022,RUF,Caye Donat,Delayed
80,phfnHI,Cordie,Rosenberger,Female,3,Brazil,Spirit of St Louis Airport,US,United States,NAM,North America,7/17/2022,SUS,Enrica Ferrarini,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98594,cxDx66,Ban,Rottger,Male,5,Spain,Gao Airport,ML,Mali,AF,Africa,11/18/2022,GAQ,Joice Rives,Cancelled
98596,H3HzS1,Giselle,Peyton,Female,7,Egypt,Iqaluit Airport,CA,Canada,NAM,North America,05-04-2022,YFB,Marris Juster,On Time
98605,7t9cZR,Morganne,Ockenden,Female,7,China,Newport Municipal Airport,US,United States,NAM,North America,09-07-2022,ONP,Hercules Shurmore,On Time
98607,rqUg8x,Rosalie,Waldock,Female,6,Thailand,Trombetas Airport,BR,Brazil,SAM,South America,12-08-2022,TMT,Dannie Guerrazzi,On Time
98618,8JYEcz,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Auguste Tindley,Delayed

In [14]:
df['First Name'][df['Age'] == df['Age'].max()]

170       Pamella
199        Sydney
206        Vernen
273       Mariann
358      Jermaine
           ...
98092         Ian
98211      Linnet
98226     Filippo
98253       Marve
98552       Liuka
Name: First Name, Length: 1076, dtype: object

In [15]:
df[df['Age'] == df['Age'].max()]

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
170,to75jW,Pamella,Eaden,Female,90,Indonesia,Amchitka Army Airfield,US,United States,NAM,North America,06-07-2022,AHT,Pearle Assiter,Cancelled
199,Zlsjqw,Sydney,MacGhee,Male,90,Guatemala,El Petén Airport,GT,Guatemala,NAM,North America,05-05-2022,TKM,Ambur Boden,On Time
206,aogYWd,Vernen,Ivakhnov,Male,90,China,Mullewa Airport,AU,Australia,OC,Oceania,09-10-2022,MXU,Lidia Kleinert,Delayed
273,X0basI,Mariann,Moogan,Female,90,Philippines,São Miguel do Oeste Airport,BR,Brazil,SAM,South America,06-02-2022,SQX,Bertrand Cauldwell,On Time
358,N7DLfQ,Jermaine,Escott,Male,90,Portugal,Northeast Alabama Regional Airport,US,United States,NAM,North America,7/15/2022,GAD,Freedman Concannon,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98092,uQoe6n,Ian,Proudlove,Male,90,Gambia,Tuzla International Airport,BA,Bosnia and Herzegovina,EU,Europe,2/26/2022,TZL,Megen Burgin,Delayed
98211,aIaf11,Linnet,Reedie,Female,90,South Korea,Fort Nelson Airport,CA,Canada,NAM,North America,11/20/2022,YYE,Giulio Downham,Delayed
98226,FOn03V,Filippo,Pays,Male,90,Colombia,Tyndall Air Force Base,US,United States,NAM,North America,06-10-2022,PAM,Janetta Howsego,Cancelled
98253,Ic4WhE,Marve,Mongain,Male,90,Indonesia,Chenega Bay Airport,US,United States,NAM,North America,3/13/2022,NCN,Lorilyn McCory,On Time
98552,D1q05w,Liuka,Caffrey,Female,90,Dominican Republic,Gooding Municipal Airport,US,United States,NAM,North America,03-02-2022,GNG,Mahmud Gabbitis,Cancelled

In [16]:
df['Age'].std()

25.929848552073015

In [17]:
df['Flight Status'].max()

'On Time'

In [18]:
df.describe()

                Age
count  98619.000000
mean      45.504021
std       25.929849
min        1.000000
25%       23.000000
50%       46.000000
75%       68.000000
max       90.000000

# List of all pandas operations

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

# set_index

In [21]:
df.set_index('Departure Date')

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Arrival Airport,Pilot Name,Flight Status
Departure Date,,,,,,,,,,,,,,
6/28/2022,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,CXF,Fransisco Hazeldine,On Time
12/26/2022,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,YCO,Marla Parsonage,On Time
1/18/2022,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,GNB,Rhonda Amber,On Time
9/16/2022,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,YND,Kacie Commucci,Delayed
2/25/2022,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,SEE,Ebonee Tree,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12-11-2022,hnGQ62,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,HAA,Pammie Kingscote,Cancelled
10/30/2022,2omEzh,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,IVA,Dorice Lochran,Cancelled
09-10-2022,VUPiVG,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,ABC,Gearalt Main,On Time
10/26/2022,E47NtS,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,GGN,Judon Chasle,Cancelled
4/16/2022,8JYEcz,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,JOK,Auguste Tindley,Delayed

In [22]:
df.set_index('Departure Date', inplace = True)

In [23]:
df

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Arrival Airport,Pilot Name,Flight Status
Departure Date,,,,,,,,,,,,,,
6/28/2022,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,CXF,Fransisco Hazeldine,On Time
12/26/2022,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,YCO,Marla Parsonage,On Time
1/18/2022,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,GNB,Rhonda Amber,On Time
9/16/2022,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,YND,Kacie Commucci,Delayed
2/25/2022,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,SEE,Ebonee Tree,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12-11-2022,hnGQ62,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,HAA,Pammie Kingscote,Cancelled
10/30/2022,2omEzh,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,IVA,Dorice Lochran,Cancelled
09-10-2022,VUPiVG,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,ABC,Gearalt Main,On Time
10/26/2022,E47NtS,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,GGN,Judon Chasle,Cancelled
4/16/2022,8JYEcz,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,JOK,Auguste Tindley,Delayed

In [24]:
df.index

Index(['6/28/2022', '12/26/2022', '1/18/2022', '9/16/2022', '2/25/2022',
       '06-10-2022', '10/30/2022', '04-07-2022', '8/20/2022', '04-06-2022',
       ...
       '4/23/2022', '08-05-2022', '06-06-2022', '3/17/2022', '05-12-2022',
       '12-11-2022', '10/30/2022', '09-10-2022', '10/26/2022', '4/16/2022'],
      dtype='object', name='Departure Date', length=98619)

In [25]:
df.loc['6/26/2022']

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Arrival Airport,Pilot Name,Flight Status
Departure Date,,,,,,,,,,,,,,
6/26/2022,oQ85WQ,Dorella,Nund,Female,75,China,Jacquinot Bay Airport,PG,Papua New Guinea,OC,Oceania,JAQ,Bethina Loram,Cancelled
6/26/2022,ydvBmF,Kristoffer,Kitchinham,Male,68,Czech Republic,Asaloyeh Airport,IR,"Iran, Islamic Republic of",AS,Asia,YEH,Aviva Wincer,Delayed
6/26/2022,33MTLm,Stacee,Dulson,Male,88,Philippines,Cortland County Chase Field,US,United States,NAM,North America,CTX,Auberta Mertgen,On Time
6/26/2022,lgyDZo,Flss,Keenlyside,Female,64,China,Wilbarger County Airport,US,United States,NAM,North America,WIB,Kirsten Falkus,On Time
6/26/2022,xWU5nL,Florenza,Trotton,Female,85,France,Yasser Arafat International Airport,PS,"Palestine, State of",AS,Asia,GZA,Belia Aloshikin,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6/26/2022,MB7plG,Artie,Wilby,Male,54,Philippines,Tuticorin Airport,IN,India,AS,Asia,TCR,Chlo Hugnin,On Time
6/26/2022,vCz7nI,Hyacinthia,Wickling,Female,79,Indonesia,Kalakaket Creek AS Airport,US,United States,NAM,North America,KKK,Teresa Cruickshank,On Time
6/26/2022,gMw1eg,Hamish,Sullly,Male,89,China,Gangaw Airport,MM,Myanmar,AS,Asia,GAW,Fransisco Cissen,Delayed
6/26/2022,ptBiPc,Sayre,Gergus,Female,1,Sweden,Roseberth Airport,AU,Australia,OC,Oceania,RSB,Mathias Peverell,Delayed
6/26/2022,e3CHO7,Dorian,Amoore,Female,75,China,Kastelorizo Airport,GR,Greece,EU,Europe,KZS,Townsend Finlan,On Time

In [26]:
df.reset_index(inplace = True)
df.head()

,Departure Date,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Arrival Airport,Pilot Name,Flight Status
0,6/28/2022,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,CXF,Fransisco Hazeldine,On Time
1,12/26/2022,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,YCO,Marla Parsonage,On Time
2,1/18/2022,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,GNB,Rhonda Amber,On Time
3,9/16/2022,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,YND,Kacie Commucci,Delayed
4,2/25/2022,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,SEE,Ebonee Tree,On Time